server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#    hostname: localhost
#    ip-address: 127.0.0.1
#instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**