server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8001
          predicates:
            - Path=/user/**
        - id: car-service
          uri: http://localhost:8002
          predicates:
            - Path=/car/**
        - id: bike-service
          uri: http://localhost:8003
          predicates:
            - Path=/bike/**