server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: b6-ms-gateway
          uri: https://github.com/ever5390/MS-Vehicles-Sales
          search-paths: config-data

application:
  name: config-service