server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: b5-ms-eureka-server
          uri: https://github.com/ever5390/MS-Vehicles-Sales
          search-paths: config-data

application:
  name: config-service